module Util
(Var "activitiesObjects",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = True})
(Var "createList",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = True})
(Var "createList'",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = True})
(Var "errors",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = True})
(Var "errors'",Value {args = 2, fixity = Def, priority = 9, letBound = True, traced = True})
(Var "groupsObjects",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = True})
(Var "participantsLogins",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = True})
(Var "participantsObjects",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = True})
(Var "possibleToList",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = True})
(Var "readConstraints",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = True})
(Var "readHeader",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = True})
(Var "readInt",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = True})
(Var "readObjects",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = True})
(Var "readTree",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = True})
(Var "repartition",Value {args = 4, fixity = Def, priority = 9, letBound = True, traced = True})
(Var "repartition'",Value {args = 5, fixity = Def, priority = 9, letBound = True, traced = True})
(Var "repartition2",Value {args = 2, fixity = Def, priority = 9, letBound = True, traced = True})
(Var "repartition2'",Value {args = 3, fixity = Def, priority = 9, letBound = True, traced = True})
(Var "repartitionUniform",Value {args = 5, fixity = Def, priority = 9, letBound = True, traced = True})
(Var "resourcesNames",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = True})
(Var "resourcesObjects",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = True})
(Var "rolesObjects",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = True})
(Var "showObjects",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = True})
(Var "splitList",Value {args = 2, fixity = Def, priority = 9, letBound = True, traced = True})
(Var "splitList2",Value {args = 3, fixity = Def, priority = 9, letBound = True, traced = True})
(Var "splitList2'",Value {args = 3, fixity = Def, priority = 9, letBound = True, traced = True})
(Var "stripFooter",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = True})
(Var "stripHeader",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = True})
(Var "writeT2",Value {args = 4, fixity = Def, priority = 9, letBound = True, traced = True})
(Var "writeT2Err",Value {args = 2, fixity = Def, priority = 9, letBound = True, traced = True})
(Con Data "Possible" "NotPossible",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = True})
(Con Data "Possible" "Possible",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = True})
(TypeClass "Activity",TyCls (Syn 0 THelper))
(TypeClass "ActivityObjects",TyCls (Syn 0 THelper))
(TypeClass "City",TyCls (Syn 0 THelper))
(TypeClass "Country",TyCls (Syn 0 THelper))
(TypeClass "Description",TyCls (Syn 0 THelper))
(TypeClass "Email",TyCls (Syn 0 THelper))
(TypeClass "FirstName",TyCls (Syn 0 THelper))
(TypeClass "Group",TyCls (Syn 0 THelper))
(TypeClass "GroupObjects",TyCls (Syn 0 THelper))
(TypeClass "Login",TyCls (Syn 0 THelper))
(TypeClass "MoodleResourceID",TyCls (Syn 0 THelper))
(TypeClass "MoodleTableName",TyCls (Syn 0 THelper))
(TypeClass "Name",TyCls (Syn 0 THelper))
(TypeClass "Participant",TyCls (Syn 0 THelper))
(TypeClass "ParticipantObjects",TyCls (Syn 0 THelper))
(TypeClass "PatternObjects",TyCls (Syn 0 THelper))
(TypeClass "Possible",TyCls (Ty ["Possible","NotPossible"] []))
(TypeClass "Resource",TyCls (Syn 0 THelper))
(TypeClass "ResourceObjects",TyCls (Syn 0 THelper))
(TypeClass "Role",TyCls (Syn 0 THelper))
(TypeClass "RoleObjects",TyCls (Syn 0 THelper))
(TypeClass "Surname",TyCls (Syn 0 THelper))
(TypeClass "TeacherNotes",TyCls (Syn 0 THelper))
